---
- name : Install the required softwares
  hosts : all
  tasks :
      - name : Install softwares
        apt :
          name : "{{item}}"
          state : present
          update_cache : yes
        with_items:
          - maven
          - git
          - openjdk-11-jdk
          - tomcat9
          - tomcat9-admin


- name: Continuous download and continous biuld
  hosts: devserver
  tasks:
    - name: Implementing continuous Download
      git: 
        repo: http://github.com/intelliqittrainings/maven.git
        dest: /dev-git
          
    - name: create an artifact
      shell: cd /dev-git; mvn package
        
    - name: fetch artifact from dev server to controller
      fetch: 
        src: /dev-git/webapp/target/webapp.war
        dest: /tmp

- name: Continuos deployment and continuous testing
  hosts: qaserver
  tasks:
    - name: deploy the war file on tomcat
      copy:
        src: /tmp/172.31.46.204/dev-git/webapp/target/webapp.war
        dest: /etc/tomcat9/webapps/testapp.war
    - name: download selenium code from github
      git:
        repo: http://github.com/intelliqittrainings/FunctionalTesting.git
        dest: /test-git
    - name: Execute the selenium scripts
      shell: java -jar /test-git/testing.jar

- name: Continuous delivery
  hosts: prodserver
  tasks:
    - name: delivery
      copy: 
        src: /tmp/172.31.46.204/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/prodapp.war






...
