---
- name: Implementing tags
  hosts: all
  become: yes
  gather_facts: false
  tasks: 
  - name: install tree
    apt:
      name: tree
      state: present
      update_cache: yes
    tags: tree installation
  - name: Create a user
    user: 
      name: prasad
      password: mohan
    tags: user creation
  - name : copy password file
    copy: 
      src: /etc/passwd
      dest: /tmp/    

...
