---
- name : Configuring Handlers
  hosts : all
  tasks : 
    - name : Installing Apache server
      apt : 
        name : apache2
        state : present
        update_cache : yes
      notify: Check the Apache server response    
    - name : Modifying the index.html file
      copy :
          content : "Welcome 2 the Devops & AWS- Ansible"
          dest : /var/www/html/index.html
      notify : Restart apache server
          #- name : Restart apache server
          #service : 
          #name : apache2
          #state : restarted 
          #


  handlers : 
      
    - name : Check the Apache server response
      uri :
        url : http://172.31.44.89
        status_code : 200

    - name : Restart apache server
      service :
        name : apache2
        state : restarted
      notify : Check the Apache server response




...
