---
- name: Install apache2 on Ubuntu and Install httpd on RedHat server
  hosts: all
  tasks:
    - name: Install apache2 on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install httpd on RedHat server
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: modify index.html file
      copy: 
        content: "Modified the login screen Apache"
        dest: /var/www/html/index.html

    - name: Restart apache server
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"

    - name: Restart https server
      service: 
        name: httpd
        state: restarted
      when: ansible_distribution == 'RedHat'

    - name: Check Url Response
      uri:
        url: "{{item}}"
        status_code: 200

      with_items:
        - http://172.31.46.204
        - http://172.31.35.48
        - http://172.31.36.139   



...
